### ISSUE TITLE
wicketd inventory test failed after 10s timeout

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#2651]
On final approach for #2570 after sync'ing up with "main" and running `SKIP_ASIC_CONFIG=1 cargo test`, I saw this failure:

```
     Running tests/mod.rs (target/debug/deps/mod-f65009c38c9a4762)

running 4 tests
test integration_tests::commands::test_wicketd_openapi ... ok
test integration_tests::inventory::test_inventory ... FAILED
test integration_tests::updates::test_updates ... ok
test integration_tests::updates::test_installinator_fetch ... ok

failures:

---- integration_tests::inventory::test_inventory stdout ----
log file: /dangerzone/omicron_tmp/mod-f65009c38c9a4762-test_inventory.23025.1.log
note: configured to log to "/dangerzone/omicron_tmp/mod-f65009c38c9a4762-test_inventory.23025.1.log"
thread 'integration_tests::inventory::test_inventory' panicked at 'get_inventory completed within 10 seconds: Elapsed(())', wicketd/tests/integration_tests/inventory.rs:42:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    integration_tests::inventory::test_inventory

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.97s
```

It seems to be pretty reproducible because I saw it when I ran it again:

```
$ cargo test -p wicketd --test mod integration_tests::inventory::test_inventory
...
    Finished test [unoptimized + debuginfo] target(s) in 1m 44s
     Running tests/mod.rs (target/debug/deps/mod-9d019d0a0c24c8ff)

running 1 test
test integration_tests::inventory::test_inventory ... FAILED

failures:

---- integration_tests::inventory::test_inventory stdout ----
log file: /dangerzone/omicron_tmp/mod-9d019d0a0c24c8ff-test_inventory.23350.0.log
note: configured to log to "/dangerzone/omicron_tmp/mod-9d019d0a0c24c8ff-test_inventory.23350.0.log"
thread 'integration_tests::inventory::test_inventory' panicked at 'get_inventory completed within 10 seconds: Elapsed(())', wicketd/tests/integration_tests/inventory.rs:42:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    integration_tests::inventory::test_inventory

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.76s

error: test failed, to rerun pass `-p wicketd --test mod`
```

**Comment by davepacheco** [comment]
Attaching the log files from these two failures.
[mod-f65009c38c9a4762-test_inventory.23025.1.log](https://github.com/oxidecomputer/omicron/files/11054826/mod-f65009c38c9a4762-test_inventory.23025.1.log)
[mod-9d019d0a0c24c8ff-test_inventory.23350.0.log](https://github.com/oxidecomputer/omicron/files/11054827/mod-9d019d0a0c24c8ff-test_inventory.23350.0.log)

**Comment by sunshowers** [comment]
@davepacheco hey, I'm not sure what's going on there -- is this with main + #2570 or just on main itself? CI doesn't seem to have this issue and I'm not sure what's going on with you.

**Comment by sunshowers** [comment]
ok, I can repro this on illumos -- digging, thanks

**Comment by davepacheco** [comment]
Yeah, I'm not sure why we didn't see it in CI, but having done another run, it's not 100% reproducible for me either, so maybe we were just getting lucky.
