### ISSUE TITLE
Metrics endpoints take several minutes to respond

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#3620]
Fuller report TBD, just want to track it. It seems to happen on every single request to these endpoints. @davepacheco suggests it's taking all that time to DNS resolution or establish a connection, so I'm looking into that. Didn't happen when 9eac70a362b951aa333244e37caa110983b67528 was deployed, came back today when 7fe972939de3f61b7f115a19004278b2499201cb was deployed. Here are two examples in the network tab. Note the duration on the right. The duration doesn't seem to go up over time. In testing, I saw times around 5 minutes, but also around 1 minute.

<img width="1713" alt="Screenshot 2023-07-14 at 10 28 39 AM" src="https://github.com/oxidecomputer/omicron/assets/3612203/0fa0a1ab-4c5f-41dc-99db-60f1f0807fed">

Metrics endpoints make a call to clickhouse, and I confirmed in the logs that the clickhouse query happens normally at the very **end** of the several minutes. Here's an example bit of Nexus log showing normal request stuff happening at 15:24:53, and then completing at 15:27:15.

```
15:24:53.387Z DEBG 36ed3232-caf0-442b-990e-01d0c0506f1a (dropshot_external): authorize result
    action = Read
    actor = Some(Actor::SiloUser { silo_user_id: a230fbce-8256-467c-b9c9-3e7b7a1e8ae8, silo_id: 6e198f0c-c3a5-4d83-87fb-be945ac1cc16, .. })
    actor_id = a230fbce-8256-467c-b9c9-3e7b7a1e8ae8
    authenticated = true
    local_addr = 172.30.2.5:443
    method = GET
    remote_addr = 172.20.16.70:59581
    req_id = 83c4c6e1-4a47-4d27-892e-347858817b50
    resource = Silo { parent: Fleet, key: 6e198f0c-c3a5-4d83-87fb-be945ac1cc16, lookup_type: ById(6e198f0c-c3a5-4d83-87fb-be945ac1cc16) }
    result = Ok(())
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/metrics/ram_provisioned?start_time=2023-07-14T14%3A24%3A53.151Z&end_time=2023-07-14T15%3A24%3A53.151Z&limit=3000
15:27:15.904Z INFO 36ed3232-caf0-442b-990e-01d0c0506f1a (dropshot_external): request completed
    local_addr = 172.30.2.5:443
    method = GET
    remote_addr = 172.20.16.70:59581
    req_id = 83c4c6e1-4a47-4d27-892e-347858817b50
    response_code = 200
    uri = https://oxide.sys.rack2.eng.oxide.computer/v1/metrics/ram_provisioned?start_time=2023-07-14T14%3A24%3A53.151Z&end_time=2023-07-14T15%3A24%3A53.151Z&limit=3000
```

Here's the clickhouse log line. You can see the timestamp on the line is 15:27:15, right when the request completes (second line in the nexus log above) and the timestamp in the query itself is 15:24:53, when the request was originally made.

```
2023.07.14 15:27:15.897206 [ 4 ] {f3568e3c-6f4d-4455-99bd-3ae35812a1fe} <Debug> executeQuery: (from [fd00:1122:3344:107::3]:63969) SELECT * FROM oximeter.measurements_i64 WHERE timeseries_name = 'collection_target:ram_provisioned' AND timeseries_key IN (10626758380822331107) AND timestamp >= '2023-07-14 14:24:53.151000000' AND timestamp < '2023-07-14 15:24:53.151000000' ORDER BY (timeseries_name, timeseries_key, timestamp) LIMIT 3000 FORMAT JSONEachRow; (stage: Complete)
```

**Comment by david-crespo** [comment]
The problem was reproducible on a single-gimlet system running 76d51d8f4b504a6fd88b2012b00be544410a4bc8.

**Comment by david-crespo** [comment]
When I look for this log line

https://github.com/oxidecomputer/omicron/blob/fca839ccfcfba9efad015e79e707f1efaf8258af/internal-dns/src/resolver.rs#L327

I get one consistently every 20 seconds:

```
EVT22200021 # tail -10000 $LOG | grep 'lookup srv' | tail -10 | looker
14:27:52.499Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
14:28:12.551Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
14:28:32.565Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
14:28:52.581Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
14:29:12.596Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
14:29:32.611Z DEBG 25238b55-d917-4706-81ce-9382bc105db2 (ServerContext): lookup srv
    dns_name = _clickhouse._tcp.control-plane.oxide.internal
```


When I look at my screenshots of my network requests, I notice the durations are all 0.33 minutes apart from each other. So I think we are processing one request every 20 seconds. If we make a lot of requests, they will queue up, and they will start taking a _very_ long time to come back.

<img width="1713" alt="Screenshot 2023-07-14 at 10 28 39 AM" src="https://github.com/oxidecomputer/omicron/assets/3612203/053323e3-88e9-412a-918c-32dfac6dc280">
<img width="1706" alt="Screenshot 2023-07-14 at 10 28 30 AM" src="https://github.com/oxidecomputer/omicron/assets/3612203/6ab75a40-09df-4c42-8558-bba59b7cf692">
<img width="1440" alt="Screenshot 2023-07-14 at 12 13 04 PM" src="https://github.com/oxidecomputer/omicron/assets/3612203/2b9620ea-d95c-47aa-8bb6-b133043eca68">
<img width="1440" alt="Screenshot 2023-07-14 at 12 17 01 PM" src="https://github.com/oxidecomputer/omicron/assets/3612203/307e55b1-4baf-459e-a36e-e5f14cbc98bd">

**Comment by smklein** [comment]
I wrote up the following program as `testdns` to try to grok the behavior of the Client resolver with multiple DNS servers.

```rust
use std::env;
use std::net::SocketAddr;
use trust_dns_resolver::config::{
    NameServerConfig, Protocol, ResolverConfig, ResolverOpts,
};
use trust_dns_resolver::TokioAsyncResolver;

#[tokio::main]
async fn main() {
    let args: Vec<String> = env::args().collect();
    let dns_addrs = args[1..].into_iter().map(|arg| {
        arg.parse::<SocketAddr>().expect("Cannot parse as socket address")
    }).collect::<Vec<_>>();

    let mut rc = ResolverConfig::new();
    for socket_addr in dns_addrs.into_iter() {
        rc.add_name_server(NameServerConfig {
            socket_addr,
            protocol: Protocol::Udp,
            tls_dns_name: None,
            trust_nx_responses: false,
            bind_addr: None,
        });
    }
    let opts = ResolverOpts::default();
    let resolver = TokioAsyncResolver::tokio(rc, opts).expect("Failed to create resolver");

    let name = "_clickhouse._tcp.control-plane.oxide.internal";

    let lookup = resolver.lookup_ip(name).await.expect("Failed to lookup IP");
    println!("IP: {lookup:?}");

}
```

Here's the results for a few different values on sn21.

```
# These are the IPs of the DNS servers
$ zoneadm list | grep internal_dns | xargs -I{} zlogin {} ipadm | grep omicron6
oxControlService1/omicron6 static ok    fd00:1122:3344:3::1/64
oxControlService2/omicron6 static ok    fd00:1122:3344:1::1/64
oxControlService3/omicron6 static ok    fd00:1122:3344:2::1/6

# One DNS server, completes immediately with success
$ ./testdns [fd00:1122:3344:1::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 13273, tv_nsec: 146527707 } })

# Same output with all DNS servers
$ ./testdns [fd00:1122:3344:1::1]:53 [fd00:1122:3344:2::1]:53 [fd00:1122:3344:3::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 13320, tv_nsec: 628973340 } })

# Same output with the DNS servers in the subnet which aren't allocated
$ ./testdns [fd00:1122:3344:1::1]:53 [fd00:1122:3344:2::1]:53 [fd00:1122:3344:3::1]:53 [fd00:1122:3344:4::1]:53 [fd00:1122:3344:5::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 13373, tv_nsec: 364726205 } })

# If we cannot route to an IP address, it fails 
$ ./testdns [fd00:1122:3344:5::1]:53
thread 'main' panicked at 'Failed to lookup IP: ResolveError { kind: Proto(ProtoError { kind: Io(Os { code: 148, kind: HostUnreachable, message: "No route to host" }) }) }', src/main.rs:30:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by smklein** [comment]
Interestingly, if I provide a routeable IP address, but where no DNS server is running, we appear to timeout in ~30 seconds:

```bash
$ time ./testdns [fd00:1122:3344:1::1]:52
thread 'main' panicked at 'Failed to lookup IP: ResolveError { kind: Timeout }', src/main.rs:30:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

real    0m30.044s
user    0m0.041s
sys     0m0.040s
```

**Comment by smklein** [comment]
Okay, out of curiosity, I tried to make the `testdns` program callable from an even-more realistic environment. I copied it into one of the Nexus zones:

```bash
# Baseline, in global zone
$ time ./testdns  [fd00:1122:3344:1::1]:53 [fd00:1122:3344:2::1]:53 [fd00:1122:3344:3::1]:53 [fd00:1122:3344:4::1]:53 [fd00:1122:3344:5::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 14753, tv_nsec: 87071211 } })

real    0m0.034s
user    0m0.034s
sys     0m0.040s

$ cp testdns /zone/oxz_nexus_25238b55-d917-4706-81ce-9382bc105db2/root/bin/
$ zlogin oxz_nexus_25238b55-d917-4706-81ce-9382bc105db2

# Within the Nexus zone, this takes **way** longer! 
(nexus-zone) $ time testdns  [fd00:1122:3344:1::1]:53 [fd00:1122:3344:2::1]:53 [fd00:1122:3344:3::1]:53 [fd00:1122:3344:4::1]:53 [fd00:1122:3344:5::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 14803, tv_nsec: 782060540 } })

real    0m5.039s
user    0m0.037s
sys     0m0.040s

# If I only send the request to the DNS servers I **know** are online, it completes immediately
(nexus-zone) $ time testdns  [fd00:1122:3344:1::1]:53 [fd00:1122:3344:2::1]:53 [fd00:1122:3344:3::1]:53
IP: LookupIp(Lookup { query: Query { name: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, records: [Record { name_labels: Name("0ff2cef1-0e56-4d87-8f02-8040e8ab24af.host.control-plane.oxide.internal."), rr_type: AAAA, dns_class: IN, ttl: 0, rdata: Some(AAAA(fd00:1122:3344:101::e)) }], valid_until: Instant { tv_sec: 14860, tv_nsec: 150395728 } })

real    0m0.034s
user    0m0.034s
sys     0m0.039s

# Sending a request to a "known-nonexistent" DNS server takes a long time
(nexus-zone) $ time testdns  [fd00:1122:3344:5::1]:53                                                  
thread 'main' panicked at 'Failed to lookup IP: ResolveError { kind: Timeout }', src/main.rs:30:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

real    0m30.139s
user    0m0.041s
sys     0m0.051s
```
