### ISSUE TITLE
panic in sync_switch_configuration.rs with "bgp config is present but announce set is not populated"

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#5361]
During today's dogfood mupdate, we found a core dump on gc08 (rsync'd over to `/staff/dock/rack2/mupdate-20240329/cores/sled-08/core.oxz_nexus_65a11c18-7f59-41ac-b9e7-680627f996e7.nexus.5125.1711667683`).

Based on timestamps, this corresponds to this message in the log file `/pool/ext/8a199f12-4f5c-483a-8aca-f97856658a35/crypt/debug/oxz_nexus_65a11c18-7f59-41ac-b9e7-680627f996e7/oxide-nexus:default.log.1711677599`:

```
thread 'tokio-runtime-worker' panicked at nexus/src/app/background/sync_switch_configuration.rs:735:26: 
bgp config is present but announce set is not populated
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ Mar 28 23:14:43 Stopping because all processes in service exited. ]
[ Mar 28 23:14:43 Executing stop method (:kill). ]
```

The assertion is [here](https://github.com/oxidecomputer/omicron/blob/17510a64780b86733b39300cfea9946f9623f0dd/nexus/src/app/background/sync_switch_configuration.rs#L735).

cc @internet-diglett who this code annotates to, and @rcgoodfellow for the nearby TODO.

**Comment by sunshowers** [comment]
Note that this corresponded to some network flakiness that was going on around that time (2024-03-28T23:14:41.638474412Z).

**Comment by rcgoodfellow** [comment]
I believe CRDB may have been unavailable during this time?

**Comment by rcgoodfellow** [comment]
Looks like it, just above the panic I see

```
23:14:41.465Z WARN 65a11c18-7f59-41ac-b9e7-680627f996e7 (ServerContext): failed to read DNS config
    background_task = dns_config_internal
    current_generation = 1
    current_time_created = 2023-08-30 18:59:10.774294 UTC
    dns_group = internal
    error = Service Unavailable: Failed to access DB connection: Timed out in bb8
    file = nexus/src/app/background/dns_config.rs:72
```

**Comment by wfchandler** [comment]
Another instance of this seen on colo sled 20 at 2025-06-13T18:02.

```
thread 'tokio-runtime-worker' panicked at nexus/src/app/background/tasks/sync_switch_configuration.rs:894:26:
bgp config is present but announce set is not populated
```

As before we see DB connection issues immediately prior:

```
17:57:59.941Z ERRO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): error checking if volume id 767c8144-06ee-487f-92b1-fb514f0edb50 was deleted: Service Unavailable: Failed to access DB connection: Backends exist, and a
ppear online, but all claims are used
    background_task = region_replacement
    file = nexus/src/app/background/tasks/region_replacement.rs:210
17:57:59.949Z ERRO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): error while fetching bgp announcements from db
    background_task = switch_port_config_manager
    bgp_announce_set_id = 6708ccb3-1692-4e11-b969-3bc87475d32d
    error = Service Unavailable: Failed to access DB connection: Backends exist, and appear online, but all claims are used
    file = nexus/src/app/background/tasks/sync_switch_configuration.rs:579
    location = switch1
    rack_id = 48759651-d754-43e2-ad49-64dde3adc1c2
17:57:59.949Z ERRO 95ebe94d-0e68-421d-9260-c30bd7fe4bd6 (ServerContext): no prefixes to announce found for bgp config
    announce_set_id = 6708ccb3-1692-4e11-b969-3bc87475d32d
    background_task = switch_port_config_manager
    bgp_config_id = 6cd5ea03-2a64-4f9a-b469-c337c44795a6
    file = nexus/src/app/background/tasks/sync_switch_configuration.rs:777
    rack_id = 48759651-d754-43e2-ad49-64dde3adc1c2
    switch = Switch1
```

Full nexus log saved to `/staff/core/omicron-5631`.
