### ISSUE TITLE
test failed in CI: `app::background::driver::test::test_driver_basic`

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#6613]
This test failed on a CI run on #6603:

https://github.com/oxidecomputer/omicron/pull/6603/checks?check_run_id=30399448658

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01J85ZJQQHSQYXSX2BT3X3KNBK/pjoCOI1My8qunRsAjyrKjQadYn8KAOJzf3QLcfZ5QdEEN0uE/01J85ZK561XN91D5Q3HFEB70QG#S4817

Excerpt from the log showing the failure:

```
--- STDOUT:              omicron-nexus app::background::driver::test::test_driver_basic ---

running 1 test
rx1 -> 3 took 1.021090936s
test app::background::driver::test::test_driver_basic ... FAILED

failures:

failures:
    app::background::driver::test::test_driver_basic

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 131 filtered out; finished in 24.29s


--- STDERR:              omicron-nexus app::background::driver::test::test_driver_basic ---
log file: /var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.0.log
note: configured to log to "/var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.0.log"
DB URL: postgresql://root@[::1]:50802/omicron?sslmode=disable
DB address: [::1]:50802
log file: /var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.2.log
note: configured to log to "/var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.2.log"
log file: /var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.3.log
note: configured to log to "/var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.3.log"
thread 'app::background::driver::test::test_driver_basic' panicked at nexus/src/app/background/driver.rs:573:9:
took longer than 1s to activate our every-100ms-task three times
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: {async_fn#0}
             at ./src/app/background/driver.rs:573:9
   3: {async_block#0}
             at ./src/app/background/driver.rs:506:5
   4: poll<&mut dyn core::future::future::Future<Output=()>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/future/future.rs:123:9
   5: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/future/future.rs:123:9
   6: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:673:57
   7: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/coop.rs:107:5
   8: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/coop.rs:73:5
   9: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:673:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:412:19
  11: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:672:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:751:68
  13: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context/scoped.rs:40:9
  14: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context.rs:180:26
  15: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:283:12
  16: std::thread::local::LocalKey<T>::with
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:260:9
  17: tokio::runtime::context::set_scheduler
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context.rs:180:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:751:27
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:660:19
  20: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:180:28
  21: tokio::runtime::context::runtime::enter_runtime
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context/runtime.rs:65:16
  22: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/current_thread/mod.rs:168:9
  23: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/runtime.rs:361:47
  24: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/runtime.rs:335:13
  25: test_driver_basic
             at ./src/app/background/driver.rs:506:5
  26: omicron_nexus::app::background::driver::test::test_driver_basic::{{closure}}
             at ./src/app/background/driver.rs:507:68
  27: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
WARN: dropped CockroachInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: temporary directory leaked: "/var/tmp/omicron_tmp/.tmpwux2X3"
	If you would like to access the database for debugging, run the following:

	# Run the database
	cargo xtask db-dev run --no-populate --store-dir "/var/tmp/omicron_tmp/.tmpwux2X3/data"
	# Access the database. Note the port may change if you run multiple databases.
	cockroach sql --host=localhost:32221 --insecure
WARN: dropped ClickHouse process without cleaning it up first (there may still be a child process running (PID 10178) and a temporary directory leaked, /var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.1-clickhouse-yFCaSj)
failed to clean up ClickHouse data dir:
- /var/tmp/omicron_tmp/omicron_nexus-2b99ae55b2439760-test_driver_basic.10149.1-clickhouse-yFCaSj: File exists (os error 17)
WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmpCvVeqr
WARN: dropped DendriteInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: dendrite temporary directory leaked: /var/tmp/omicron_tmp/.tmp8oGK70
WARN: dropped MgdInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: mgd temporary directory leaked: /var/tmp/omicron_tmp/.tmpFHSKG7
WARN: dropped MgdInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: mgd temporary directory leaked: /var/tmp/omicron_tmp/.tmpvrYHg8

```

**Comment by davepacheco** [comment]
The key is:

```
thread 'app::background::driver::test::test_driver_basic' panicked at nexus/src/app/background/driver.rs:573:9:
took longer than 1s to activate our every-100ms-task three times
```

Above, we have the actual duration that it took to activate this task three times: 1.021090936s.  So we _did_ activate it three times successfully -- it just took a little longer than we expected (by 2.1%).  I'm guessing we've just got a busy test runner here and so I'm inclined to bump up the margin a bit more.

**Comment by bnaecker** [comment]
I hit this again [here](https://buildomat.eng.oxide.computer/wg/0/details/01JKE7WG2PCJ4XM40TE7YGXHGK/S1BLK4w93UZUojkL9hlFcOI77lH7Ci9Hxofnh1PAEsTlbKFW/01JKE7WY4NFB58VEHP1KK85HXD#S5825). @davepacheco I'm not sure it's important to bump this timeout any further, but I wanted to record the flake.

**Comment by davepacheco** [comment]
This one took 1.442196774s.  I mean, that is an awfully long time to do something that should only take about 300ms.  If you'd asked me ahead of time I would say that's slow enough to be effectively broken.  But if it _is_ just a CPU-starved test runner, then that's not really a bug, and we could bump the timeout further.  To what?  If the assumption is test runners can be _really_ busy, then the point of the timeout is just to avoid hanging when the thing is obviously broken.  So...10s?  30s?

**Comment by hawkw** [comment]
If it's useful, I just hit this one again too, on #7508: https://buildomat.eng.oxide.computer/wg/0/details/01JKV95X51ATNR72B2KJZ1S0WT/xP68GcgadOFxPVxQ9TWnNSISwhjlfp6nfx6FLPu9dlHXbf67/01JKV969ZKMADWX6NZZB346SKQ#S6409

**Comment by davepacheco** [comment]
Ugh, sorry.  That one took:

> 1.40064932s
