### ISSUE TITLE
test failed in CI: test_instance_ephemeral_ip_from_correct_pool

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#7072]
This test failed on a CI run on https://github.com/oxidecomputer/omicron/pull/6996:

https://github.com/oxidecomputer/omicron/pull/6996/checks?check_run_id=32997420847

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01JCNQZ3ZPYBZG21K4SHG2NAT4/cB71BeZO4zYrsy689IeJAbnxqqyVcSK9G8eKIZdE1Cwmmbsm/01JCNQZT856DJ4SVBCAWWE4PJY

Excerpt from the log showing the failure:

```
6459	2024-11-14T17:02:04.658Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 397 filtered out; finished in 159.09s
6460	2024-11-14T17:02:04.658Z	
6461	2024-11-14T17:02:04.658Z	
6462	2024-11-14T17:02:04.658Z	--- STDERR:              omicron-nexus::test_all integration_tests::instances::test_instance_ephemeral_ip_from_correct_pool ---
6463	2024-11-14T17:02:04.658Z	log file: /var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.0.log
6464	2024-11-14T17:02:04.658Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.0.log"
6465	2024-11-14T17:02:04.658Z	DB URL: postgresql://root@[::1]:33983/omicron?sslmode=disable
6466	2024-11-14T17:02:04.658Z	DB address: [::1]:33983
6467	2024-11-14T17:02:04.658Z	log file: /var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.2.log
6468	2024-11-14T17:02:04.658Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.2.log"
6469	2024-11-14T17:02:04.658Z	log file: /var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.3.log
6470	2024-11-14T17:02:04.658Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-2d920668872ead29-test_instance_ephemeral_ip_from_correct_pool.134374.3.log"
6471	2024-11-14T17:02:04.658Z	thread 'integration_tests::instances::test_instance_ephemeral_ip_from_correct_pool' panicked at nexus/tests/integration_tests/instances.rs:6129:19:
6472	2024-11-14T17:02:04.658Z	instance 31bfba3b-e21a-4b54-b140-5418c564ccfe did not transition to Stopped after 120s: timed out after 120.895399649s
6473	2024-11-14T17:02:04.658Z	stack backtrace:
6474	2024-11-14T17:02:04.658Z	   0: rust_begin_unwind
6475	2024-11-14T17:02:04.658Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
6476	2024-11-14T17:02:04.658Z	   1: core::panicking::panic_fmt
6477	2024-11-14T17:02:04.658Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
6478	2024-11-14T17:02:04.658Z	   2: {async_fn#0}
6479	2024-11-14T17:02:04.659Z	             at ./tests/integration_tests/instances.rs:6129:19
6480	2024-11-14T17:02:04.659Z	   3: {async_fn#0}
6481	2024-11-14T17:02:04.659Z	             at ./tests/integration_tests/instances.rs:6080:6
6482	2024-11-14T17:02:04.659Z	   4: {async_fn#0}
6483	2024-11-14T17:02:04.659Z	             at ./tests/integration_tests/instances.rs:5472:74
6484	2024-11-14T17:02:04.659Z	   5: {async_fn#0}
6485	2024-11-14T17:02:04.659Z	             at ./tests/integration_tests/instances.rs:5418:56
6486	2024-11-14T17:02:04.659Z	   6: {async_block#0}
6487	2024-11-14T17:02:04.659Z	             at ./tests/integration_tests/instances.rs:5315:1
6488	2024-11-14T17:02:04.659Z	   7: poll<&mut dyn core::future::future::Future<Output=()>>
6489	2024-11-14T17:02:04.659Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
6490	2024-11-14T17:02:04.659Z	   8: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
6491	2024-11-14T17:02:04.659Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
6492	2024-11-14T17:02:04.659Z	   9: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
6493	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
6494	2024-11-14T17:02:04.659Z	  10: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
6495	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
6496	2024-11-14T17:02:04.659Z	  11: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
6497	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
6498	2024-11-14T17:02:04.659Z	  12: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
6499	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
6500	2024-11-14T17:02:04.659Z	  13: tokio::runtime::scheduler::current_thread::Context::enter
6501	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
6502	2024-11-14T17:02:04.659Z	  14: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
6503	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
6504	2024-11-14T17:02:04.659Z	  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
6505	2024-11-14T17:02:04.659Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
6506	2024-11-14T17:02:04.659Z	  16: tokio::runtime::context::scoped::Scoped<T>::set
6507	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
6508	2024-11-14T17:02:04.660Z	  17: tokio::runtime::context::set_scheduler::{{closure}}
6509	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
6510	2024-11-14T17:02:04.660Z	  18: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
6511	2024-11-14T17:02:04.660Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:283:12
6512	2024-11-14T17:02:04.660Z	  19: std::thread::local::LocalKey<T>::with
6513	2024-11-14T17:02:04.660Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:260:9
6514	2024-11-14T17:02:04.660Z	  20: tokio::runtime::context::set_scheduler
6515	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
6516	2024-11-14T17:02:04.660Z	  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
6517	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
6518	2024-11-14T17:02:04.660Z	  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
6519	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
6520	2024-11-14T17:02:04.660Z	  23: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
6521	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
6522	2024-11-14T17:02:04.660Z	  24: tokio::runtime::context::runtime::enter_runtime
6523	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
6524	2024-11-14T17:02:04.660Z	  25: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
6525	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9
6526	2024-11-14T17:02:04.660Z	  26: tokio::runtime::runtime::Runtime::block_on_inner
6527	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47
6528	2024-11-14T17:02:04.660Z	  27: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
6529	2024-11-14T17:02:04.660Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
6530	2024-11-14T17:02:04.660Z	  28: test_instance_ephemeral_ip_from_correct_pool
6531	2024-11-14T17:02:04.660Z	             at ./tests/integration_tests/instances.rs:5315:1
6532	2024-11-14T17:02:04.660Z	  29: test_all::integration_tests::instances::test_instance_ephemeral_ip_from_correct_pool::{{closure}}
6533	2024-11-14T17:02:04.660Z	             at ./tests/integration_tests/instances.rs:5318:2
6534	2024-11-14T17:02:04.664Z	  30: core::ops::function::FnOnce::call_once
6535	2024-11-14T17:02:04.664Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
6536	2024-11-14T17:02:04.664Z	  31: core::ops::function::FnOnce::call_once
6537	2024-11-14T17:02:04.664Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
```

**Comment by gjcolombo** [comment]
Another hit from #7791: https://buildomat.eng.oxide.computer/wg/0/details/01JRBX2VKX5JR5ZR8HE10VK1VK/2wDMTxKHsGp8k8SOCSc2KnvhHwo6mKDjHuCo0VPG5bZvuMcN/01JRBX3JXS8MMS8GQN2VQ983HM

```
[7612]	2025-04-09T00:29:57.965Z	thread 'integration_tests::instances::test_instance_ephemeral_ip_from_correct_pool' panicked at sled-agent/src/sim/collection.rs:274:65:
[7613]	2025-04-09T00:29:57.965Z	called `Result::unwrap()` on an `Err` value: InternalError { internal_message: "Communication Error: error sending request for url (http://127.0.0.1:44163/vmms/95a87919-341b-4f3f-8d4c-aab6160e6e7d)" }
[7614]	2025-04-09T00:29:57.965Z	stack backtrace:
[7615]	2025-04-09T00:29:57.965Z	   0: rust_begin_unwind
[7616]	2025-04-09T00:29:57.965Z	             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
[7617]	2025-04-09T00:29:57.965Z	   1: core::panicking::panic_fmt
[7618]	2025-04-09T00:29:57.965Z	             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
[7619]	2025-04-09T00:29:57.965Z	   2: core::result::unwrap_failed
[7620]	2025-04-09T00:29:57.965Z	             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/result.rs:1704:5
[7621]	2025-04-09T00:29:57.965Z	   3: unwrap<(), omicron_common::api::external::error::Error>
[7622]	2025-04-09T00:29:57.966Z	             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/result.rs:1109:23
[7623]	2025-04-09T00:29:57.966Z	   4: {async_fn#0}<omicron_sled_agent::sim::instance::SimInstance>
[7624]	2025-04-09T00:29:57.966Z	             at /work/oxidecomputer/omicron/sled-agent/src/sim/collection.rs:274:13
[7625]	2025-04-09T00:29:57.966Z	   5: {async_fn#0}
[7626]	2025-04-09T00:29:57.966Z	             at /work/oxidecomputer/omicron/sled-agent/src/sim/sled_agent.rs:529:58
[7627]	2025-04-09T00:29:57.966Z	   6: {async_fn#0}
[7628]	2025-04-09T00:29:57.966Z	             at /work/oxidecomputer/omicron/sled-agent/src/sim/http_entrypoints.rs:789:38
```

Simulated sled agent has been asked to simulate an instance state change, and it unwrapped a `CommunicationError` from its attempt to call `cpapi_instances_put` to notify Nexus of the new VMM state. I am unsure why this happened; the logs suggest that the test isn't anywhere near finished yet (it's calling `stop_and_delete_instance` on the instance `pool1-inst` that it previously created), and the Nexus that was the callee of this operation (port 44163) reports a completed request after the instance `poke` handler finishes.
