### ISSUE TITLE
test failed in CI: test_disk_metrics

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#7073]
This test failed on a CI run on https://github.com/oxidecomputer/omicron/pull/6996:

https://github.com/oxidecomputer/omicron/pull/6996/checks?check_run_id=32997420398

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01JCNQZ3ZPYBZG21K4SHG2NAT4/cB71BeZO4zYrsy689IeJAbnxqqyVcSK9G8eKIZdE1Cwmmbsm/01JCNQZT82ET6VJ2Q7TFJW8JX7

Excerpt from the log showing the failure:

```
5780	2024-11-14T17:46:42.083Z	--- STDOUT:              omicron-nexus::test_all integration_tests::disks::test_disk_metrics ---
5781	2024-11-14T17:46:42.083Z	
5782	2024-11-14T17:46:42.084Z	running 1 test
5783	2024-11-14T17:46:42.084Z	sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(15123565), kind: System }, version: Some(RouterVersion { router_id: 69d6ff4a-b785-497a-b86e-b814aac93872, version: 3 }), routes: {ResolvedVpcRoute { dest: V6(Ipv6Net { addr: fdbb:ad88:7f1c::, width: 64 }), target: VpcSubnet(V6(Ipv6Net { addr: fdbb:ad88:7f1c::, width: 64 })) }, ResolvedVpcRoute { dest: V4(Ipv4Net { addr: 172.30.0.0, width: 22 }), target: VpcSubnet(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, ResolvedVpcRoute { dest: V6(Ipv6Net { addr: ::, width: 0 }), target: InternetGateway(Some(934f59d5-054b-47db-befb-ad1a3fa7aba4)) }, ResolvedVpcRoute { dest: V4(Ipv4Net { addr: 0.0.0.0, width: 0 }), target: InternetGateway(Some(934f59d5-054b-47db-befb-ad1a3fa7aba4)) }} }
5784	2024-11-14T17:46:42.084Z	sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(15123565), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
5785	2024-11-14T17:46:42.084Z	sled b6d65341-167c-41df-9b5c-41cded99c229 successfully installed routes ResolvedVpcRouteSet { id: RouterId { vni: Vni(15123565), kind: Custom(V4(Ipv4Net { addr: 172.30.0.0, width: 22 })) }, version: None, routes: {} }
5786	2024-11-14T17:46:42.084Z	test integration_tests::disks::test_disk_metrics ... FAILED
5787	2024-11-14T17:46:42.084Z	
5788	2024-11-14T17:46:42.084Z	failures:
5789	2024-11-14T17:46:42.084Z	
5790	2024-11-14T17:46:42.084Z	failures:
5791	2024-11-14T17:46:42.084Z	    integration_tests::disks::test_disk_metrics
5792	2024-11-14T17:46:42.084Z	
5793	2024-11-14T17:46:42.084Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 397 filtered out; finished in 39.92s
5794	2024-11-14T17:46:42.084Z	
5795	2024-11-14T17:46:42.084Z	
5796	2024-11-14T17:46:42.084Z	--- STDERR:              omicron-nexus::test_all integration_tests::disks::test_disk_metrics ---
5797	2024-11-14T17:46:42.084Z	log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.0.log
5798	2024-11-14T17:46:42.084Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.0.log"
5799	2024-11-14T17:46:42.085Z	DB URL: postgresql://root@[::1]:47962/omicron?sslmode=disable
5800	2024-11-14T17:46:42.085Z	DB address: [::1]:47962
5801	2024-11-14T17:46:42.085Z	log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.2.log
5802	2024-11-14T17:46:42.085Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.2.log"
5803	2024-11-14T17:46:42.085Z	log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.3.log
5804	2024-11-14T17:46:42.085Z	note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_disk_metrics.17151.3.log"
5805	2024-11-14T17:46:42.085Z	thread 'integration_tests::disks::test_disk_metrics' panicked at /work/oxidecomputer/omicron/nexus/test-utils/src/resource_helpers.rs:75:10:
5806	2024-11-14T17:46:42.085Z	failed to make request: expected status code 200 OK, found 503 Service Unavailable
5807	2024-11-14T17:46:42.085Z	
5808	2024-11-14T17:46:42.085Z	Stack backtrace:
5809	2024-11-14T17:46:42.085Z	   0: anyhow::error::<impl anyhow::Error>::msg
5810	2024-11-14T17:46:42.085Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/backtrace.rs:27:14
5811	2024-11-14T17:46:42.085Z	   1: {async_fn#0}
5812	2024-11-14T17:46:42.085Z	             at ./test-utils/src/http_testing.rs:339:13
5813	2024-11-14T17:46:42.085Z	   2: {async_fn#0}
5814	2024-11-14T17:46:42.085Z	             at ./test-utils/src/http_testing.rs:612:40
5815	2024-11-14T17:46:42.085Z	   3: {async_fn#0}<oximeter_types::types::Measurement>
5816	2024-11-14T17:46:42.085Z	             at ./test-utils/src/resource_helpers.rs:74:10
5817	2024-11-14T17:46:42.086Z	   4: {async_fn#0}
5818	2024-11-14T17:46:42.086Z	             at ./tests/integration_tests/metrics.rs:38:47
5819	2024-11-14T17:46:42.086Z	   5: {async_fn#0}
5820	2024-11-14T17:46:42.086Z	             at ./tests/integration_tests/disks.rs:1847:75
5821	2024-11-14T17:46:42.086Z	   6: {async_block#0}
5822	2024-11-14T17:46:42.086Z	             at ./tests/integration_tests/disks.rs:1800:1
5823	2024-11-14T17:46:42.086Z	   7: poll<&mut dyn core::future::future::Future<Output=()>>
5824	2024-11-14T17:46:42.086Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
5825	2024-11-14T17:46:42.086Z	   8: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5826	2024-11-14T17:46:42.086Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
5827	2024-11-14T17:46:42.086Z	   9: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5828	2024-11-14T17:46:42.086Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
5829	2024-11-14T17:46:42.086Z	  10: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5830	2024-11-14T17:46:42.086Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
5831	2024-11-14T17:46:42.086Z	  11: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5832	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
5833	2024-11-14T17:46:42.087Z	  12: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5834	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
5835	2024-11-14T17:46:42.087Z	  13: tokio::runtime::scheduler::current_thread::Context::enter
5836	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
5837	2024-11-14T17:46:42.087Z	  14: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5838	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
5839	2024-11-14T17:46:42.087Z	  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
5840	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
5841	2024-11-14T17:46:42.087Z	  16: tokio::runtime::context::scoped::Scoped<T>::set
5842	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
5843	2024-11-14T17:46:42.087Z	  17: tokio::runtime::context::set_scheduler::{{closure}}
5844	2024-11-14T17:46:42.087Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
5845	2024-11-14T17:46:42.087Z	  18: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
5846	2024-11-14T17:46:42.088Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:283:12
5847	2024-11-14T17:46:42.088Z	  19: std::thread::local::LocalKey<T>::with
5848	2024-11-14T17:46:42.088Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:260:9
5849	2024-11-14T17:46:42.088Z	  20: tokio::runtime::context::set_scheduler
5850	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
5851	2024-11-14T17:46:42.088Z	  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
5852	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
5853	2024-11-14T17:46:42.088Z	  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
5854	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
5855	2024-11-14T17:46:42.088Z	  23: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5856	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
5857	2024-11-14T17:46:42.088Z	  24: tokio::runtime::context::runtime::enter_runtime
5858	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
5859	2024-11-14T17:46:42.088Z	  25: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5860	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9
5861	2024-11-14T17:46:42.088Z	  26: tokio::runtime::runtime::Runtime::block_on_inner
5862	2024-11-14T17:46:42.088Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47
5863	2024-11-14T17:46:42.089Z	  27: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5864	2024-11-14T17:46:42.089Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
5865	2024-11-14T17:46:42.089Z	  28: test_disk_metrics
5866	2024-11-14T17:46:42.089Z	             at ./tests/integration_tests/disks.rs:1800:1
5867	2024-11-14T17:46:42.089Z	  29: test_all::integration_tests::disks::test_disk_metrics::{{closure}}
5868	2024-11-14T17:46:42.089Z	             at ./tests/integration_tests/disks.rs:1801:64
5869	2024-11-14T17:46:42.089Z	  30: core::ops::function::FnOnce::call_once
5870	2024-11-14T17:46:42.089Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
5871	2024-11-14T17:46:42.089Z	  31: core::ops::function::FnOnce::call_once
5872	2024-11-14T17:46:42.089Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
5873	2024-11-14T17:46:42.089Z	  32: test::__rust_begin_short_backtrace
5874	2024-11-14T17:46:42.089Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs:624:18
5875	2024-11-14T17:46:42.090Z	  33: test::run_test_in_process::{{closure}}
5876	2024-11-14T17:46:42.090Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs:647:60
5877	2024-11-14T17:46:42.090Z	  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
5878	2024-11-14T17:46:42.096Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
5879	2024-11-14T17:46:42.096Z	  35: std::panicking::try::do_call
5880	2024-11-14T17:46:42.096Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
5881	2024-11-14T17:46:42.096Z	  36: std::panicking::try
5882	2024-11-14T17:46:42.096Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
5883	2024-11-14T17:46:42.096Z	  37: std::panic::catch_unwind
5884	2024-11-14T17:46:42.096Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
5885	2024-11-14T17:46:42.096Z	  38: test::run_test_in_process
5886	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs:647:27
5887	2024-11-14T17:46:42.097Z	  39: test::run_test::{{closure}}
5888	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs:568:43
5889	2024-11-14T17:46:42.097Z	  40: test::run_test::{{closure}}
5890	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/test/src/lib.rs:598:41
5891	2024-11-14T17:46:42.097Z	  41: std::sys::backtrace::__rust_begin_short_backtrace
5892	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
5893	2024-11-14T17:46:42.097Z	  42: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
5894	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:538:17
5895	2024-11-14T17:46:42.097Z	  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
5896	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
5897	2024-11-14T17:46:42.097Z	  44: std::panicking::try::do_call
5898	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
5899	2024-11-14T17:46:42.097Z	  45: std::panicking::try
5900	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
5901	2024-11-14T17:46:42.097Z	  46: std::panic::catch_unwind
5902	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
5903	2024-11-14T17:46:42.097Z	  47: std::thread::Builder::spawn_unchecked_::{{closure}}
5904	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:537:30
5905	2024-11-14T17:46:42.097Z	  48: core::ops::function::FnOnce::call_once{{vtable.shim}}
5906	2024-11-14T17:46:42.097Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
5907	2024-11-14T17:46:42.098Z	  49: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
5908	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
5909	2024-11-14T17:46:42.098Z	  50: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
5910	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
5911	2024-11-14T17:46:42.098Z	  51: std::sys::pal::unix::thread::Thread::new::thread_start
5912	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/pal/unix/thread.rs:108:17
5913	2024-11-14T17:46:42.098Z	  52: _thrp_setup
5914	2024-11-14T17:46:42.098Z	  53: <unknown>
5915	2024-11-14T17:46:42.098Z	stack backtrace:
5916	2024-11-14T17:46:42.098Z	   0: rust_begin_unwind
5917	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
5918	2024-11-14T17:46:42.098Z	   1: core::panicking::panic_fmt
5919	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
5920	2024-11-14T17:46:42.098Z	   2: core::result::unwrap_failed
5921	2024-11-14T17:46:42.098Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
5922	2024-11-14T17:46:42.098Z	   3: core::result::Result<T,E>::expect
5923	2024-11-14T17:46:42.099Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1059:23
5924	2024-11-14T17:46:42.099Z	   4: {async_fn#0}<oximeter_types::types::Measurement>
5925	2024-11-14T17:46:42.099Z	             at ./test-utils/src/resource_helpers.rs:71:5
5926	2024-11-14T17:46:42.099Z	   5: {async_fn#0}
5927	2024-11-14T17:46:42.099Z	             at ./tests/integration_tests/metrics.rs:38:47
5928	2024-11-14T17:46:42.099Z	   6: {async_fn#0}
5929	2024-11-14T17:46:42.099Z	             at ./tests/integration_tests/disks.rs:1847:75
5930	2024-11-14T17:46:42.099Z	   7: {async_block#0}
5931	2024-11-14T17:46:42.099Z	             at ./tests/integration_tests/disks.rs:1800:1
5932	2024-11-14T17:46:42.099Z	   8: poll<&mut dyn core::future::future::Future<Output=()>>
5933	2024-11-14T17:46:42.099Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
5934	2024-11-14T17:46:42.099Z	   9: poll<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5935	2024-11-14T17:46:42.099Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
5936	2024-11-14T17:46:42.099Z	  10: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5937	2024-11-14T17:46:42.099Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
5938	2024-11-14T17:46:42.099Z	  11: with_budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5939	2024-11-14T17:46:42.099Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
5940	2024-11-14T17:46:42.099Z	  12: budget<core::task::poll::Poll<()>, tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure#0}::{closure#0}::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
5941	2024-11-14T17:46:42.099Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
5942	2024-11-14T17:46:42.099Z	  13: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5943	2024-11-14T17:46:42.099Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
5944	2024-11-14T17:46:42.099Z	  14: tokio::runtime::scheduler::current_thread::Context::enter
5945	2024-11-14T17:46:42.099Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
5946	2024-11-14T17:46:42.100Z	  15: {closure#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
5947	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
5948	2024-11-14T17:46:42.100Z	  16: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
5949	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
5950	2024-11-14T17:46:42.100Z	  17: tokio::runtime::context::scoped::Scoped<T>::set
5951	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
5952	2024-11-14T17:46:42.100Z	  18: tokio::runtime::context::set_scheduler::{{closure}}
5953	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
5954	2024-11-14T17:46:42.100Z	  19: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>), tokio::runtime::scheduler::current_thread::{impl#8}::enter::{closure_env#0}<tokio::runtime::scheduler::current_thread::{impl#8}::block_on::{closure_env#0}<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>, core::option::Option<()>>>, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core, alloc::alloc::Global>, core::option::Option<()>)>
5955	2024-11-14T17:46:42.100Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:283:12
5956	2024-11-14T17:46:42.100Z	  20: std::thread::local::LocalKey<T>::with
5957	2024-11-14T17:46:42.100Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:260:9
5958	2024-11-14T17:46:42.100Z	  21: tokio::runtime::context::set_scheduler
5959	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
5960	2024-11-14T17:46:42.100Z	  22: tokio::runtime::scheduler::current_thread::CoreGuard::enter
5961	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
5962	2024-11-14T17:46:42.100Z	  23: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
5963	2024-11-14T17:46:42.100Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
5964	2024-11-14T17:46:42.101Z	  24: {closure#0}<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5965	2024-11-14T17:46:42.101Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
5966	2024-11-14T17:46:42.101Z	  25: tokio::runtime::context::runtime::enter_runtime
5967	2024-11-14T17:46:42.101Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
5968	2024-11-14T17:46:42.101Z	  26: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5969	2024-11-14T17:46:42.101Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9
5970	2024-11-14T17:46:42.101Z	  27: tokio::runtime::runtime::Runtime::block_on_inner
5971	2024-11-14T17:46:42.102Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47
5972	2024-11-14T17:46:42.102Z	  28: block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
5973	2024-11-14T17:46:42.102Z	             at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
5974	2024-11-14T17:46:42.102Z	  29: test_disk_metrics
5975	2024-11-14T17:46:42.102Z	             at ./tests/integration_tests/disks.rs:1800:1
5976	2024-11-14T17:46:42.102Z	  30: test_all::integration_tests::disks::test_disk_metrics::{{closure}}
5977	2024-11-14T17:46:42.102Z	             at ./tests/integration_tests/disks.rs:1801:64
5978	2024-11-14T17:46:42.106Z	  31: core::ops::function::FnOnce::call_once
5979	2024-11-14T17:46:42.106Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
5980	2024-11-14T17:46:42.106Z	  32: core::ops::function::FnOnce::call_once
5981	2024-11-14T17:46:42.106Z	             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
```

**Comment by smklein** [comment]
Unraveling the backtrace:

https://github.com/oxidecomputer/omicron/blob/main/nexus/tests/integration_tests/disks.rs#L1847

is calling

https://github.com/oxidecomputer/omicron/blob/3589f79c5135b034337b36b1da5f4f5220d43b14/nexus/tests/integration_tests/metrics.rs#L37-L40

This points fingers at either Nexus, Oximeter, or Clickhouse, IMO.

From the Nexus logs, I see:

```
	test_disk_metrics (dropshot_external): request completed
    error_message_external = Service Unavailable
    error_message_internal = Telemetry database unavailable: error sending request for url (http://[::1]:37169/?output_format_json_quote_64bit_integers=0&wait_end_of_query=1)
    latency_us = 169699
    local_addr = 127.0.0.1:59103
    method = GET
    remote_addr = 127.0.0.1:42324
    req_id = c5be68f7-8be0-4b37-8134-10f6a7159402
    response_code = 503
    uri = /v1/disks/just-rainsticks/metrics/activated?start_time=2024-11-14T17:46:01.709441165Z&end_time=2024-11-14T17:46:40.292358961Z&project=springfield-squidport-disks
```

**Comment by smklein** [comment]
Looks like `Telemetry database unavailable` comes from the `DatabaseUnavailable` error in oximeter's client.

This therefore looks like an issue communicating between the Oximeter client -> Clickhouse
