### ISSUE TITLE
test failure: oximeter-collector agent::tests::verify_producer_details

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#7220]
On branch `nexus-support-bundles-api` commit https://github.com/oxidecomputer/omicron/pull/7008/commits/04612605174b44fe00b5fd40a42dcbf86fcdf6f9, I saw this test failure:

```
[6361](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6361)	2024-12-10T04:16:39.841Z	--- STDOUT:              oximeter-collector agent::tests::verify_producer_details ---
[6362](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6362)	2024-12-10T04:16:39.841Z	
[6363](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6363)	2024-12-10T04:16:39.841Z	running 1 test
[6364](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6364)	2024-12-10T04:16:39.841Z	test agent::tests::verify_producer_details ... FAILED
[6365](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6365)	2024-12-10T04:16:39.841Z	
[6366](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6366)	2024-12-10T04:16:39.841Z	failures:
[6367](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6367)	2024-12-10T04:16:39.841Z	
[6368](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6368)	2024-12-10T04:16:39.841Z	failures:
[6369](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6369)	2024-12-10T04:16:39.841Z	    agent::tests::verify_producer_details
[6370](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6370)	2024-12-10T04:16:39.841Z	
[6371](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6371)	2024-12-10T04:16:39.841Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 7 filtered out; finished in 2.42s
[6372](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6372)	2024-12-10T04:16:39.841Z	
[6373](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6373)	2024-12-10T04:16:39.841Z	
[6374](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6374)	2024-12-10T04:16:39.841Z	--- STDERR:              oximeter-collector agent::tests::verify_producer_details ---
[6375](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6375)	2024-12-10T04:16:39.841Z	log file: /var/tmp/omicron_tmp/oximeter_collector-8d360fb04fde51d8-verify_producer_details.27004.0.log
[6376](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6376)	2024-12-10T04:16:39.841Z	note: configured to log to "/var/tmp/omicron_tmp/oximeter_collector-8d360fb04fde51d8-verify_producer_details.27004.0.log"
[6377](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6377)	2024-12-10T04:16:39.841Z	thread 'agent::tests::verify_producer_details' panicked at oximeter/collector/src/agent.rs:993:34:
[6378](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6378)	2024-12-10T04:16:39.841Z	Should have a successful collection


[6434](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6434)	2024-12-10T04:16:39.843Z	  27: verify_producer_details
[6435](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6435)	2024-12-10T04:16:39.843Z	             at ./src/agent.rs:998:9
[6436](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6436)	2024-12-10T04:16:39.843Z	  28: oximeter_collector::agent::tests::verify_producer_details::{{closure}}
[6437](https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6437)	2024-12-10T04:16:39.843Z	             at ./src/agent.rs:930:39

```

From https://buildomat.eng.oxide.computer/wg/0/details/01JEQ4WFJEWDA6198H3B2CK6ZB/2kMDwVMdgcVPfuOzsafBTNN6KDbMwJaUla9o3q4TKLXJkxJ7/01JEQ4XB1JV4YKKB20RP6ADAXD#S6359

**Comment by smklein** [comment]
100% certain this is flake - a downstream branch passed, and the code in this branch is fully unrelated from oximeter
